name: Make Clean Branch

on:
  push:
    branches:
      - main

env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  changes:
    runs-on: arc-runner-set
    container:
      image: asia-northeast3-docker.pkg.dev/manythings-mitosis/docker-images/arc-runner-alpine
      credentials:
        username: _json_key
        password: ${{ secrets.GOOGLE_CREDENTIAL }}

    # Set job outputs to values from filter step
    outputs:
      contracts: ${{ steps.filter.outputs.contracts }}

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_REPO_READER }}
          submodules: recursive

      - name: Resolve dubious ownership
        run: git config --global --add safe.directory /__w/${{ env.REPO_NAME }}/${{ env.REPO_NAME }}

      # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            contracts:
              - 'src/**'
              - 'foundry.toml'
              - 'soldeer.lock'
              - '.gitignore'

  clean-branch:
    needs: changes
    if: ${{ needs.changes.outputs.contracts == 'true' }}

    name: update clean branch
    runs-on: arc-runner-set
    container:
      image: asia-northeast3-docker.pkg.dev/manythings-mitosis/docker-images/arc-runner-alpine
      credentials:
        username: _json_key
        password: ${{ secrets.GOOGLE_CREDENTIAL }}

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: clean

      - name: run update
        run: |
          git config --global --add safe.directory /__w/${{ env.REPO_NAME }}/${{ env.REPO_NAME }}
          git fetch
          git checkout origin/main src foundry.toml soldeer.lock .gitignore
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "cleaned $GITHUB_SHA"
          git push
