name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CI: true
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: test
    runs-on: arc-runner-set
    container: node:20

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_REPO_READER }}
          submodules: recursive

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Yarn Install
        run: yarn install

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run Soldeer install
        run: |
          git config --global credential.https://github.com.username git
          git config --global url."https://${{ secrets.GH_REPO_READER }}@github.com/".insteadOf "https://github.com/"
          forge soldeer install -d

      - name: Show Forge version
        run: |
          forge --version

      - name: Run linter checks
        run: |
          yarn lint:check
        id: lint

      - name: Run Forge build
        run: |
          forge build
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test

      - name: Run Forge coverage
        run: |
          apt-get update
          apt-get -y install lcov
          yarn coverage
        id: coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ${{ github.repository }}
